decoder_layers:
- 64
- 128
- 256
encoder_layers:
- 256
- 128
- 64
n_cvs: 3
n_features: 936
options:
  decoder:
    activation: relu
    last_layer_activation: sigmoid
  encoder:
    activation: relu
    last_layer_activation: false
  optimizer:
    lr: 0.0001
postprocessing: null
preprocessing: null
