decoder_layers:
- 32
- 64
- 128
- 256
- 512
encoder_layers:
- 512
- 256
- 128
- 64
- 32
n_cvs: 3
n_features: 801
options:
  decoder:
    activation: relu
    last_layer_activation: sigmoid
  encoder:
    activation: relu
    last_layer_activation: false
  optimizer:
    lr: 5.0e-05
postprocessing: null
preprocessing: null
