decoder_layers:
- 16
- 32
encoder_layers:
- 32
- 16
n_cvs: 2
n_features: 804
options:
  decoder:
    activation: relu
    last_layer_activation: sigmoid
  encoder:
    activation: relu
    last_layer_activation: false
  optimizer:
    lr: 0.0001
postprocessing: null
preprocessing: null
