decoder_layers:
- 16
- 804
encoder_layers:
- 804
- 16
n_cvs: 2
options:
  decoder:
    activation: relu
    last_layer_activation: false
  encoder:
    activation: relu
    last_layer_activation: true
  optimizer:
    lr: 0.001
postprocessing: null
preprocessing: null
