decoder_layers:
- 16
- 32
- 804
encoder_layers:
- 804
- 32
- 16
n_cvs: 2
options:
  decoder:
    activation: relu
    last_layer_activation: sigmoid
  encoder:
    activation: relu
    last_layer_activation: sigmoid
  optimizer:
    lr: 0.0001
postprocessing: null
preprocessing: null
